apiVersion: v1
kind: Service
metadata:
  name: app-ca
  labels:
    app: app-ca
spec:
  type: ClusterIP
  selector:
    app: app-ca
  ports:
    - port: 9000
      targetPort: 9000
      protocol: TCP