apiVersion: v1
kind: Service
metadata:
  name: app-ca-fr
  labels:
    app: app-ca-fr
spec:
  type: ClusterIP
  selector:
    app: app-ca-fr
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-ca-fr
  labels:
    app: app-ca-fr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-ca-fr
  template:
    metadata:
      labels:
        app: app-ca-fr
    spec:
      containers:
        - name: app-ca-fr
          #          image: devcoderjava/app-ca-fr:1.0
          #          imagePullPolicy: Always
          image: app-ca-fr-local:1.0
          imagePullPolicy: Never
          ports:
            - containerPort: 80
          env:
            - name: BACKEND_URL
              value: "http://app-ca:9000"