apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-ingress
spec:
  ingressClassName: nginx
  rules:
    - host: app.local
      http:
        paths:
          # Backend users
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: app-ca
                port:
                  number: 9000
          # Frontend Angular
          - path: /
            pathType: Prefix
            backend:
              service:
                name: app-ca-fr
                port:
                  number: 80